In [1]:
#Loading Libraries
import numpy as np  
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Reading Data
df = pd.read_excel('Mini_protein_data_HA_BOT_combined_for_ml.xlsx')
print('Data downloaded and read into a dataframe!')

Data downloaded and read into a dataframe!

In [15]:
df

,Category,Category_0_1,Category_0_1-2_3_4,Category_0-1_2_3_4,Mono_total_score,Mono_AlaCount,Mono_bb,Mono_buried_minus_exposed,Mono_buried_np,Mono_buried_over_exposed,...,Core_res_w,Core_res_I,Core_total,Positive_charge_H,Positive_charge_K,Positive_charge_R,Positive_total,Negative_charge_D,Negative_charge_E,Negative_total
0,0,0,0,0,-3.20,0.19,0.00,76.22,118.59,0.07,...,0,1,5,0,8,2,10,2,6,8
1,2,0,1,1,-3.68,0.16,0.00,80.98,122.27,0.07,...,0,3,12,0,4,5,9,3,6,9
2,0,0,0,0,-3.76,0.14,0.00,83.53,125.57,0.07,...,0,3,10,0,7,2,9,1,7,8
3,0,0,0,0,-3.46,0.14,0.00,78.12,119.14,0.07,...,0,3,9,0,5,1,6,2,6,8
4,0,0,0,0,-3.04,0.14,0.00,75.43,119.45,0.06,...,1,2,8,0,9,1,10,1,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34152,0,0,0,0,-3.00,0.07,-0.01,71.21,112.45,0.07,...,1,1,6,0,2,5,7,4,5,9
34153,0,0,0,0,-1.86,0.07,-0.01,63.18,112.69,0.06,...,1,2,8,0,2,4,6,1,3,4
34154,0,0,0,0,-1.64,0.21,0.00,60.49,112.93,0.05,...,0,5,13,0,8,2,10,1,5,6
34155,0,0,0,0,-3.45,0.14,0.00,81.77,123.33,0.07,...,1,4,13,0,2,2,4,3,6,9
34156,0,0,0,0,-3.10,0.10,-0.01,76.26,118.34,0.07,...,1,1,9,1,1,5,7,1,4,5

In [19]:
df_short=df.iloc[:,[98,99,100,101,102,103,104,105,106,107]]
df_short.head()

,Complex_yhh_planarity,Len,Core_res_F,Core_res_l,Core_res_Y,Core_res_w,Core_res_I,Core_total,Positive_charge_H,Positive_charge_K
0,0.0,43,3,1,0,0,1,5,0,8
1,0.0,43,3,3,3,0,3,12,0,4
2,0.0,43,3,3,1,0,3,10,0,7
3,0.0,43,3,3,0,0,3,9,0,5
4,0.0,43,3,2,0,1,2,8,0,9

In [20]:
X = df.drop(['Category','Category_0_1','Category_0-1_2_3_4','Category_0_1-2_3_4'], axis = 1)
X.shape

(34157, 109)

In [ ]:
#Plotting_Data Distribution Original Data
sns.set(rc={'figure.figsize':(93.6,66.16)})
j=4
features = ["Mono_total_score","Mono_AlaCount","Mono_bb","Mono_buried_minus_exposed","Mono_buried_np","Mono_buried_over_exposed","Mono_cavity_volume","Mono_contact_all","Mono_contact_core_SASA","Mono_contact_core_SCN","Mono_degree","Mono_dslf_fa13","Mono_dslf_quality_check","Mono_entropy","Mono_exposed_hydrophobics","Mono_exposed_polars","Mono_exposed_total","Mono_fa_atr","Mono_fa_dun","Mono_fa_elec","Mono_fa_intra_rep","Mono_fa_intra_sol_xover4","Mono_fa_rep","Mono_fa_sol","Mono_fxn_exposed_is_np","Mono_hbond_bb_sc","Mono_hbond_lr_bb","Mono_hbond_sc","Mono_hbond_sr_bb","Mono_helix_sc","Mono_holes","Mono_lk_ball_wtd","Mono_loop_sc","Mono_mean_dslf","Mono_mismatch_probability","Mono_omega","Mono_one_core_each","Mono_p_aa_pp","Mono_pack","Mono_percent_core_SASA","Mono_percent_core_SCN","Mono_pro_close","Mono_rama_prepro","Mono_ref","Mono_res_count_core_SASA","Mono_res_count_core_SCN","Mono_ss_contributes_core","Mono_ss_sc","Mono_two_core_each","Mono_unsat_hbond","Mono_unsat_hbond2","Mono_yhh_planarity","Complex_total_score","Complex_ddg","Complex_ddg_fa_atr","Complex_ddg_fa_atr_norepack","Complex_ddg_fa_atr_norepack_per_1000sasa","Complex_ddg_fa_atr_per_1000sasa","Complex_ddg_norepack","Complex_ddg_norepack_per_1000sasa","Complex_ddg_per_1000sasa","Complex_dslf_fa13","Complex_fa_atr","Complex_fa_dun","Complex_fa_elec","Complex_fa_intra_rep","Complex_fa_intra_sol_xover4","Complex_fa_rep","Complex_fa_sol","Complex_fxn_np_chain1_buried_approx","Complex_fxn_np_chain2_buried_approx","Complex_hbond_bb_sc","Complex_hbond_lr_bb","Complex_hbond_sc","Complex_hbond_sr_bb","Complex_interface_averageDegree","Complex_interface_buried_sasa","Complex_interface_contactcount","Complex_interface_fxn_hydrophobic","Complex_interface_holes","Complex_interface_hydrophobic_sasa","Complex_interface_polar_sasa","Complex_interface_sc","Complex_interface_sc_int_area","Complex_interface_unsat_hbond","Complex_interface_unsat_hbond2","Complex_lk_ball_wtd","Complex_np_chain1_exposed_approx","Complex_np_chain2_exposed_approx","Complex_omega","Complex_p_aa_pp","Complex_pro_close","Complex_rama_prepro","Complex_ref","Complex_yhh_planarity","Len","Core_res_F","Core_res_l","Core_res_Y","Core_res_w","Core_res_I","Core_total","Positive_charge_H","Positive_charge_K","Positive_charge_R","Positive_total","Negative_charge_D","Negative_charge_E","Negative_total"]
for x in features:
    df_plot=df.iloc[:,[0,j]]
    sns_plot = sns.violinplot(df_plot)
    sns_plot.set_ylabel("Frequency",size=200)
    sns_plot.set_xlabel(str(x),size=200)
    sns_plot.set_xticklabels(sns_plot.get_xticks(), size = 160)
    fig = sns_plot.get_figure()
    fig.savefig(str(j)+"_data_distribution"+".png")
    plt.close()
    j=j+1

In [ ]:
#Plotting_Data relations Modified Categories
sns.set(font_scale=5)
for i in range (4,113):
    for j in range (4,6):
        if i != j:
            df_plot=df.iloc[:,[3,i,j]]
            sns_plot = sns.pairplot(df_plot,hue='Category_0-1_2_3_4',height=10,plot_kws={'s':900})
            g = sns_plot
            g._legend.set_title("Category")
            plt.setp(g._legend.get_title(), fontsize=70)
            g.fig.set_size_inches(55,40)
            g.savefig(str(i)+"-"+str(j)+"_feature-relations_0_1"+".png")
            plt.close()
        j=j+1
    i=i+1

/home/biplab/anaconda3/lib/python3.8/site-packages/seaborn/distributions.py:369: UserWarning: Default bandwidth for data is 0; skipping density estimation.
  warnings.warn(msg, UserWarning)
/home/biplab/anaconda3/lib/python3.8/site-packages/seaborn/distributions.py:369: UserWarning: Default bandwidth for data is 0; skipping density estimation.
  warnings.warn(msg, UserWarning)

In [ ]:
#Plotting_Data relations Original Categories
sns.set(font_scale=5)
for i in range (4,113):
    for j in range (4,6):
        if i != j:
            df_plot=df.iloc[:,[0,i,j]]
            sns_plot = sns.pairplot(df_plot,hue='Category',height=10,plot_kws={'s':900})
            g = sns_plot
            g._legend.set_title("Category")
            plt.setp(g._legend.get_title(), fontsize=70)
            g.fig.set_size_inches(55,40)
            g.savefig(str(i)+"-"+str(j)+"_feature-relations_0_1_2_3_4"+".png")
            plt.close()
        j=j+1
    i=i+1

In [4]:
#Reading Data Scalled and Transformed Features
df2 = pd.read_excel('Scalled_extracted_features.xlsx')
print('Transformed and Scalled Data loaded and read into a dataframe!')

Transformed and Scalled Data loaded and read into a dataframe!

In [6]:
#Plotting_Data Distribution Modified Data
sns.set(rc={'figure.figsize':(93.6,66.16)})
j=2
features = ["Mono_total_score","Mono_entropy","Mono_exposed_hydrophobics","Mono_exposed_total","Mono_fa_elec","Mono_fa_intra_sol_xover4","Mono_fa_sol","Mono_hbond_sr_bb","Mono_p_aa_pp","Complex_ddg_fa_atr","Complex_ddg_fa_atr_norepack","Complex_ddg_fa_atr_norepack_per_1000sasa","Complex_ddg_fa_atr_per_1000sasa","Complex_ddg_norepack_per_1000sasa","Complex_dslf_fa13","Complex_fa_dun","Complex_fa_intra_rep","Complex_fa_intra_sol_xover4","Complex_fa_rep","Complex_fa_sol","Complex_hbond_lr_bb","Complex_interface_contactcount","Complex_interface_sc_int_area","Complex_interface_unsat_hbond2","Complex_lk_ball_wtd","Complex_np_chain1_exposed_approx","Complex_np_chain2_exposed_approx","Complex_omega","Complex_p_aa_pp","Complex_pro_close","Complex_rama_prepro","Complex_yhh_planarity","Positive_charge_K","Negative_total"]
for x in features:
    df_plot=df2.iloc[:,[0,j]]
    sns_plot = sns.violinplot(df_plot)
    sns_plot.set_ylabel("Frequency",size=200)
    sns_plot.set_xlabel(str(x),size=200)
    sns_plot.set_xticklabels(sns_plot.get_xticks(), size = 160)
    fig = sns_plot.get_figure()
    fig.savefig(str(j)+"_scalled_data_distribution"+".png")
    plt.close()
    j=j+1